# Generated by Django 6.0.5 on 2026-05-18 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_establecimiento', models.CharField(max_length=100)),
                ('tipo_establecimiento', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad_pueblo_localidad', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedHospitalaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_red', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estamento', models.CharField(max_length=100)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estamentos', to='someApp.establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('genero', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('ciudad_pueblo_localidad', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('universidad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField(auto_now=True)),
                ('estamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='someApp.estamento')),
                ('red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='someApp.redhospitalaria')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_box', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('profesional_asignado', models.CharField(max_length=100)),
                ('esta_ocupado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('registros_uso', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='someApp.establecimiento')),
                ('funcionarios', models.ManyToManyField(related_name='boxes_asignados', to='someApp.funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='red',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to='someApp.redhospitalaria'),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.CharField(max_length=100)),
                ('nombre_paciente', models.CharField(max_length=200)),
                ('genero_paciente', models.CharField(max_length=50)),
                ('edad_paciente', models.CharField(max_length=10)),
                ('comuna', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('programa_salud', models.CharField(max_length=100)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='someApp.establecimiento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_atendidos', to='someApp.funcionario')),
            ],
        ),
    ]
