# Generated by Django 6.0.5 on 2026-05-19 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-9 (sin puntos y con guion).', regex='^\\d{7,8}-[\\dkK]$')]),
        ),
    ]
