# Generated by Django 6.0.5 on 2026-05-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('someApp', '0002_rename_nombre_funcionario_nombres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='edad',
        ),
    ]
