# Generated by Django 6.0.5 on 2026-05-19 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someApp', '0003_remove_funcionario_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='someApp.establecimiento'),
        ),
    ]
