# Generated by Django 6.0.5 on 2026-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someApp', '0004_funcionario_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
