# Generated by Django 6.0.5 on 2026-05-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('someApp', '0005_funcionario_edad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='Profesional',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='funcionarios',
            new_name='profesionales',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='funcionario',
            new_name='profesional',
        ),
    ]
