# Generated by Django 6.0.5 on 2026-05-19 19:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someApp', '0006_rename_funcionario_profesional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioSome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-9 (sin puntos y con guion).', regex='^\\d{7,8}-[\\dkK]$')])),
                ('genero', models.CharField(max_length=50)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=50)),
                ('ciudad_pueblo_localidad', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('universidad', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField(auto_now=True)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios_some', to='someApp.establecimiento')),
                ('red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='someApp.redhospitalaria')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.CharField(max_length=100)),
                ('nombre_paciente', models.CharField(max_length=200)),
                ('genero_paciente', models.CharField(max_length=50)),
                ('edad_paciente', models.CharField(max_length=10)),
                ('comuna', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('programa_salud', models.CharField(max_length=100)),
                ('tipo_consulta', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('tipo_atencion', models.CharField(blank=True, max_length=100, null=True)),
                ('duracion_cita', models.CharField(blank=True, max_length=50, null=True)),
                ('confirma_asistencia', models.BooleanField(default=False)),
                ('reprograma_cita', models.BooleanField(default=False)),
                ('cancela_cita', models.BooleanField(default=False)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='someApp.box')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='someApp.establecimiento')),
                ('funcionario_some', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_creadas', to='someApp.funcionariosome')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_atendidas', to='someApp.profesional')),
            ],
        ),
    ]
