# Generated by Django 6.0.5 on 2026-05-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someApp', '0007_funcionariosome_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='folio',
            field=models.PositiveIntegerField(blank=True, help_text='Folio único que se mantiene en reprogramaciones', null=True),
        ),
    ]
