# Generated by Django 6.0.5 on 2026-05-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('someApp', '0008_reserva_folio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='motivo_consulta',
        ),
    ]
