# Generated by Django 6.0.5 on 2026-05-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someApp', '0009_remove_reserva_motivo_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='duracion_cita',
            field=models.PositiveIntegerField(blank=True, help_text='Duración en minutos', null=True),
        ),
    ]
