# Generated by Django 6.0.5 on 2026-05-22 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someApp', '0010_alter_reserva_duracion_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.AutoField(primary_key=True, serialize=False)),
                ('nombreGenero', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='funcionariosome',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='someApp.genero'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='someApp.genero'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='genero_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='someApp.genero'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='genero_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='someApp.genero'),
        ),
    ]
