# Generated by Django 6.0.5 on 2026-05-22 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someApp', '0011_genero_alter_funcionariosome_genero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoProfesional',
            fields=[
                ('id_cargoProfesional', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CargoSome',
            fields=[
                ('id_cargoSome', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='profesional',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='someApp.cargoprofesional'),
        ),
        migrations.AlterField(
            model_name='funcionariosome',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='someApp.cargosome'),
        ),
    ]
