# Generated by Django 6.0.5 on 2026-05-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someApp', '0012_cargoprofesional_cargosome_alter_profesional_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoprofesional',
            name='nombre_cargo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cargosome',
            name='nombre_cargo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombreGenero',
            field=models.CharField(max_length=50),
        ),
    ]
